version: '3.0'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    network_mode: "bridge"
    ports:
      - "3306:3306"
  
  redis:
    image: redis:6.0.5-alpine
    command: redis-server
    network_mode: "bridge"
    container_name: redis
